# These are supported funding model platforms
github: [REDDRoX]
patreon: [REDDRoX]
open_collective: [REDDRoX]
ko_fi: [REDDRoX]
tidelift: [REDDRoX]
community_bridge: [REDDRoX]
liberapay: [REDDRoX]
issuehunt: [REDDRoX]
otechie: [REDDRoX]
custom: ['REDRRoX.COM', 'https://github.com/REDDRoX/TheMystic-Bot-MD','REDRRoX.COM']
